import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <meta name='description' content='Generated by harsh'/>
      <meta name='keywords' content='ttt, tttprofile, tttwebsite'/>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
